{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/home/cike/code/src",
    "dependencies": [
      "munch==2.5.0",
      "numpy==1.21.6",
      "PyYAML==5.4.1",
      "sacred==0.8.2",
      "torch==1.10.2"
    ],
    "mainfile": "meta_main.py",
    "name": "pymarl",
    "repositories": [],
    "sources": [
      [
        "meta_main.py",
        "_sources/meta_main_91b1486ec9cab37f0e46eab8767c1ebb.py"
      ],
      [
        "utils/config_utils.py",
        "_sources/config_utils_11a418cc99d65a52a4ab3d9c9e93f913.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_867f86b10403f8b7e6826558d04fb18e.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"src/meta_main.py\", line 43, in my_main\n    run(_run, config, _log)\n",
    "  File \"src/meta_main.py\", line 79, in run\n    pop = pop_REGISTRY[args.pop](args, logger)\n",
    "  File \"/home/cike/code/src/meta/population/stage1_population.py\", line 23, in __init__\n    self.individuals = self._init_individuals(self.args.population_size)\n",
    "  File \"/home/cike/code/src/meta/population/stage1_population.py\", line 43, in _init_individuals\n    return [ind_REGISTRY[self.args.ind](id, self.args, self.pp) for id in range(num)]\n",
    "  File \"/home/cike/code/src/meta/population/stage1_population.py\", line 43, in <listcomp>\n    return [ind_REGISTRY[self.args.ind](id, self.args, self.pp) for id in range(num)]\n",
    "  File \"/home/cike/code/src/meta/individual/stage1_individual.py\", line 73, in __init__\n    self.learner.cuda()\n",
    "  File \"/home/cike/code/src/learners/q_learner.py\", line 121, in cuda\n    self.mac.cuda()\n",
    "  File \"/home/cike/code/src/controllers/basic_controller.py\", line 69, in cuda\n    self.agent.cuda()\n",
    "  File \"/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 680, in cuda\n    return self._apply(lambda t: t.cuda(device))\n",
    "  File \"/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 570, in _apply\n    module._apply(fn)\n",
    "  File \"/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 593, in _apply\n    param_applied = fn(param)\n",
    "  File \"/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 680, in <lambda>\n    return self._apply(lambda t: t.cuda(device))\n",
    "RuntimeError: CUDA error: out of memory\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n"
  ],
  "heartbeat": "2024-10-19T18:39:20.709909",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz",
    "gpus": {
      "driver_version": "470.182.03",
      "gpus": [
        {
          "model": "Quadro RTX 8000",
          "persistence_mode": false,
          "total_memory": 48601
        },
        {
          "model": "Tesla P100-PCIE-16GB",
          "persistence_mode": false,
          "total_memory": 16280
        },
        {
          "model": "Tesla P100-PCIE-16GB",
          "persistence_mode": false,
          "total_memory": 16280
        },
        {
          "model": "Quadro RTX 8000",
          "persistence_mode": false,
          "total_memory": 48601
        },
        {
          "model": "Tesla P100-PCIE-16GB",
          "persistence_mode": false,
          "total_memory": 16280
        },
        {
          "model": "Tesla P100-PCIE-16GB",
          "persistence_mode": false,
          "total_memory": 16280
        }
      ]
    },
    "hostname": "89ddac7113b8",
    "os": [
      "Linux",
      "Linux-4.15.0-213-generic-x86_64-with-debian-buster-sid"
    ],
    "python_version": "3.7.12"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2024-10-19T18:39:10.292509",
  "status": "FAILED",
  "stop_time": "2024-10-19T18:39:20.712863"
}